name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        channel:
          - stable
          - beta
          - nightly
          - 1.23.0
        os:
          - macos-11
          - windows-2022
          - ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update rust
      run: |
        rustup default ${{ matrix.channel }}
        rustup update --no-self-update

    - run: cargo test --all
