name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  os_tests:
    name: "Tests / OS: ${{ matrix.os }} - ${{ matrix.channel }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        channel:
        - stable
        - beta
        - nightly
        - 1.23.0
        os:
        - macos-12
        - windows-2022
        - ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update rust
      run: rustup update ${{ matrix.channel }} --no-self-update

    - name: Tests
      run: cargo +${{ matrix.channel }} test --all
